=== QEF/qexsd/qeschema/schemas/qes_spectrum.xsd
<?xml version="1.0"?>
<!--
Copyright (c), 2015-2016, Quantum Espresso Foundation. All rights reserved.
This file is distributed under the terms of the MIT License. See the
file 'LICENSE' in the root directory of the present distribution, or
http://opensource.org/licenses/MIT.
Authors: Pietro Delugas
-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:qes_spectrum="http://www.quantum-espresso.org/ns/qes/qes_spectrum-1.0"
	targetNamespace="http://www.quantum-espresso.org/ns/qes/qes_spectrum-1.0" version="20180517">
    <element name="spectrumDoc" type="qes_spectrum:TdppOutType"/>
    <complexType name="TdppOutType">
        <sequence>
            <element name="spectrumIn" type="qes_spectrum:spectrumInType"/>
        </sequence>
    </complexType>
    <complexType name="spectrumInType">
        <sequence>
            <element name="prefix" type="string"/>
            <element name="units" type="qes_spectrum:energyUnitsType" minOccurs="0" maxOccurs="1" default="Ry"/>
            <element name="verbosity" type="integer" minOccurs="0" maxOccurs="1" default="0"/>
            <element name="outdir" type="string" minOccurs="0" maxOccurs="1" default="./"/>
            <element name="itermax" type="positiveInteger" minOccurs="0" maxOccurs="1" default="1000"/>
            <element name="itermax0" type="positiveInteger" minOccurs="0" maxOccurs="1" default="1000"/>
            <element name="itermax_actual" type="positiveInteger" minOccurs="0" maxOccurs="1"/>
            <element name="extrapolation" type="qes_spectrum:extrapolChoiceType" minOccurs="0" maxOccurs="1"/>
            <element name="start" type="double" minOccurs="0" maxOccurs="1" default="0.0"/>
            <element name="end" type="double" minOccurs="0" maxOccurs="1" default="2.5"/>
            <element name="increment" type="double" minOccurs="0" maxOccurs="1" default="0.001"/>
            <element name="ipol" type="integer" minOccurs="0" maxOccurs="1" default="1"/>

            <element name="epsil" type="double" minOccurs="0" maxOccurs="1" default="0.02"/>
            <element name="sym_op" type="integer" minOccurs="0" maxOccurs="1" default="0"/>
            <element name="td" type="qes_spectrum:tdChoiceType" minOccurs="0" maxOccurs="1" default="lanczos"/>
            <element name="io_level" type="nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
            <element name="wfcdir" type="string" minOccurs="0" maxOccurs="0"/>
            <element name="max_seconds" type="positiveInteger" minOccurs="0" maxOccurs="1"/>
            <element name="eign_file" type="string" minOccurs="0" maxOccurs="1" default="pwscf.eigen"/>
            <element name="eels" type="boolean" minOccurs="0" maxOccurs="1" default="false"/>
        </sequence>
    </complexType>
    <simpleType name="energyUnitsType">
        <restriction base="string">
            <enumeration value="Ry"/>
            <enumeration value="eV"/>
            <enumeration value="nm"/>
        </restriction>
    </simpleType>
    <simpleType name="tdChoiceType">
        <restriction base="string">
            <enumeration value="lanczos"/>
            <enumeration value="davidson"/>
        </restriction>
    </simpleType>
    <simpleType name="extrapolChoiceType">
        <restriction base="string">
            <enumeration value="no"/>
            <enumeration value="osc"/>
            <enumeration value="constant"/>
        </restriction>
    </simpleType>
</schema>

=== QEF/qexsd/tests/examples/tddfpt/CH4.tddfpt_pp.xml
<qes_spectrum:spectrumDoc xmlns:qes_spectrum="http://www.quantum-espresso.org/ns/qes/qes_spectrum-1.0"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.quantum-espresso.org/ns/qes/qes_spectrum-1.0 ../../../qeschema/schemas/qes_spectrum.xsd">
<spectrumIn>
    <prefix>CH4</prefix>
    <outdir>./out</outdir>
    <itermax>10000</itermax>
    <itermax0>500</itermax0>
    <extrapolation>osc</extrapolation>
    <start>0.0</start>
    <end>3.50</end>
    <increment>0.001</increment>
    <ipol>4</ipol>
    <epsil>0.01</epsil>
</spectrumIn>   
</qes_spectrum:spectrumDoc>

=== QEF/qexsd/examples/TDDFPT/EELS-Ag/Ag.tddfpt_pp.xml
<?xml version="1.0" encoding="UTF-8"?>
<qes_spectrum:spectrumIn xsi:schemaLocation="http://www.quantum-espresso.org/ns/qes/qes_spectrum-1.0 https://raw.githubusercontent.com/QEF/qexsd/master/qespresso/scheme/qes_spectrum.xsd"
               xmlns:qes_spectrum="http://www.quantum-espresso.org/ns/qes/qes_spectrum-1.0"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
    <prefix>Ag</prefix>
    <outdir>./out</outdir>
    <eels>true</eels>
    <itermax0>500</itermax0>
    <itermax>10000</itermax>
    <extrapolation>osc</extrapolation>
    <epsil>0.025</epsil>
    <units>eV</units>
    <start>0.0</start>
    <end>50.0</end>
    <increment>0.01</increment>
</qes_spectrum:spectrumIn>
